# Render Blueprint configuration
services:
  - type: web
    name: fitlifetracker-backend
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET  
        generateValue: true
      - key: RUN_DB_SYNC
        value: true
    healthCheckPath: /health

  - type: postgresql        # <-- change this from pgsql to postgres
    name: fitlifetracker-db
    plan: free
    region: ohio
    ipAllowList: []
    databaseName: fitlifetracker
    user: fitlifetracker_user
